local RDX_translation = {
	
	-- SPELL
	["(Rank 1)"] = "(Rang 1)",
	["(Rank 2)"] = "(Rang 2)",
	["Rank (%d+)"] = "Rang (%d+)",
	
	-- Priest
	["Renew"] = "Rénovation",
	["Lesser Heal"] = "Soins inférieurs",
	["Heal"] = "Soins",
	["Greater Heal"] = "Soins supérieurs",
	["Flash Heal"] = "Soins rapides",
	["Binding Heal"] = "Soins de lien",
	["Prayer of Healing"] = "Prière de soins",
	["Prayer of Mending"] = "Prière de guérison",
	["Power Infusion"] = "Infusion de puissance",
	["Lightwell"] = "Puits de lumière",
	["Fear Ward"] = "Gardien de peur",
	["Pain Suppression"] = "Suppression de la douleur",
	["Shadowfiend"] = "Ombrefiel",
	["Resurrection"] = "Résurrection",
	["Divine Spirit"] = "Esprit divin",
	["Prayer of Spirit"] = "Prière d'Esprit",
	["Power Word: Fortitude"] = "Mot de pouvoir : Robustesse",
	["Prayer of Fortitude"] = "Prière de robustesse",
	["Shadow Protection"] = "Protection contre l'ombre",
	["Prayer of Shadow Protection"] = "Prière de protection contre l'Ombre",
	["Shackle Undead"] = "Entraves des morts-vivants",
	["Spirit of Redemption"] = "Esprit de rédemption",
	
	-- Druid
	["Regrowth"] = "Rétablissement",
	["Rejuvenation"] = "Récupération",
	["Healing Touch"] = "Toucher guérisseur",
	["Innervate"] = "Innervation",
	["Rebirth"] = "Renaissance",
	["Challenging Roar"] = "Rugissement provocateur",
	["Rebirth"] = "Renaissance",
	["Mark of the Wild"] = "Marque du fauve",
	["Gift of the Wild"] = "Don du fauve",
	["Thorns"] = "Epines",
	["Lifebloom"] = "Fleur de vie",
	["Hibernate"] = "Hibernation",
	
	-- Paladin
	["Holy Light"] = "Lumière sacrée",
	["Flash of Light"] = "Eclair lumineux",
	["Lay on Hands"] = "Imposition des mains",
	["Divine Intervention"] = "Intervention divine",
	["Blessing of Protection"] = "Bénédiction de protection",
	["Redemption"] = "Rédemption",
	["Blessing of Kings"] = "Bénédiction des rois",
	["Greater Blessing of Kings"] = "Bénédiction des rois Supérieure",
	["Blessing of Wisdom"] = "Bénédiction de sagesse",
	["Greater Blessing of Wisdom"] = "Bénédiction de sagesse Supérieure",
	["Blessing of Salvation"] = "Bénédiction de salut",
	["Greater Blessing of Salvation"] = "Bénédiction de salut Supérieure",
	["Blessing of Might"] = "Bénédiction de puissance",
	["Greater Blessing of Might"] = "Bénédiction de puissance Supérieure",
	["Blessing of Sanctuary"] = "Bénédiction du Sanctuaire",
	["Greater Blessing of Sanctuary"] = "Bénédiction du Sanctuaire Supérieure",
	["Blessing of Light"] = "Bénédiction de lumière",
	["Greater Blessing of Light"] = "Bénédiction de lumière Supérieure",
	
	-- Shaman
	["Healing Wave"] = "Vague de soins",
	["Lesser Healing Wave"] = "Vague de soins inférieurs",
	["Chain Heal"] = "Salve de guérison",
	["Mana Tide Totem"] = "Vague de mana",
	["Nature's Swiftness"] = "Rapidité de la nature",
	["Heroism"] = "Héroïsme",
	["Bloodlust"] = "Furie sanguinaire",
	["Earth Shock"] = "Horion de terre",
	["Reincarnation"] = "Réincarnation",
	["Improved Reincarnation"] = "Réincarnation améliorée",
	["Ancestral Spirit"] = "Esprit ancestral",
	
	["You cast (.+)."] = "Vous lancez (.+).",
	
	["Stoneskin Totem"] = "Totem de Peau de pierre",
	["Earthbind Totem"] = "Totem de lien terrestre",
	["Stoneclaw Totem"] = "Totem de Griffes de pierre",
	["Earth Elemental Totem"] =  "Totem d'élémentaire de terre",
	["Strength of Earth Totem"] = "Totem de Force de la Terre",
	["Tremor Totem"] = "Totem de Séisme",
	
	["Totem of Wrath"] = "Totem de courroux",
	["Searing Totem"] = "Totem incendiaire",
	["Magma Totem"] = "Totem de Magma",
	["Frost Resistance Totem"] = "Totem de résistance au Givre",
	["Fire Elemental Totem"] = "Totem d'élémentaire de Feu",
	["Flametongue Totem"] = "Totem Langue de feu",
	["Fire Nova Totem"] = "Totem Nova de feu",
	
	["Disease Cleansing Totem"] = "Totem de Purification des maladies",
	["Fire Resistance Totem"] = "Totem de résistance au Feu",
	["Healing Stream Totem"] = "Totem guérisseur",
	["Mana Spring Totem"] = "Totem Fontaine de mana",
	["Mana Tide Totem"] = "Totem de Vague de mana",
	["Poison Cleansing Totem"] = "Totem de Purification du poison",
	["Enamored Water Spirit"] = "Totem de l'eau amoureux",
	
	["Grace of Air Totem"] = "Totem de Grâce aérienne",
	["Grounding Totem"] = "Totem de Glèbe",
	["Nature Resistance Totem"] = "Totem de résistance à la Nature",
	["Sentry Totem"] = "Totem Sentinelle",
	["Tranquil Air Totem"] = "Totem de Tranquillité de l'air",
	["Windfury Totem"] = "Totem Furie-des-vents",
	["Windwall Totem"] = "Totem de Mur des vents",
	["Wrath of Air Totem"] = "Totem de courroux de l'air",
	
	["Totemic Call"] = "Appel totémique",
	
	-- Warrior
	["Challenging Shout"] = "Cri de défi",
	["Shield Wall"] = "Mur protecteur",
	["Last Stand"] = "Dernier rempart",
	["Shield Bash"] = "Coup de bouclier",
	["Pummel"] = "Volée de coups",
	--["Lifegiving Gem"] = "",
	--["Gift of Life"] = "",
	["Intervene"] = "Intervention",
	
	-- Hunter
	["Misdirection"] = "Détournement",
	["Freezing Trap"] = "Piège givrant",
	
	-- Mage
	["Counterspell"] = "Contresort",
	["Arcane Intellect"] = "Intelligence des arcanes",
	["Arcane Brilliance"] = "Illumination des arcanes",
	["Polymorph"] = "Métamorphose",
	
	-- Rogue
	["Kick"] = "Coup de pied",
	["Sap"] = "Assommer",
	
	-- Warlock
	["Soulstone"] = "Pierre d'âme",
	["Soulstone Resurrection"] = "Résurrection de Pierre d'âme",
	["Unending Breath"] = "Respiration interminable",
	["Fear"] = "Peur",
	["Banish"] = "Bannir",
	["Curse of Recklessness"] = "Malédiction de témérité",
	["Curse of Weakness"] = "Malédiction de faiblesse",
	["Curse of Tongues"] = "Malédiction des langages",
	["Curse of the Elements"] = "Malédiction des éléments",
	["Curse of Shadow"] = "Malédiction de l'ombre",
	
	-- all
	["Dispel Magic"] = "Dissipation de la magie",
	["Cure Disease"] = "Guérison des maladies",
	["Abolish Disease"] = "Abolir maladie",
	["Cleanse"] = "Epuration",
	["Cure Poison"] = "Guérison du poison",
	["Abolish Poison"] = "Abolir le poison",
	["Remove Curse"] = "Délivrance de la malédiction",
	["Remove Lesser Curse"] = "Délivrance de la malédiction mineure",
	
	-- weaponbuff
	["Anesthetic Poison"] = "Poison anesthésiant",	
	["Instant Poison"] = "Poison instantané",
	["Instant Poison II"] = "Poison instantané II",
	["Instant Poison III"] = "Poison instantané III",
	["Instant Poison IV"] = "Poison instantané IV",
	["Instant Poison V"] = "Poison instantané V",
	["Instant Poison VI"] = "Poison instantané VI",
	["Instant Poison VII"] = "Poison instantané VII",
	["Wound Poison"] = "Poison affaiblissant",
	["Wound Poison II"] = "Poison affaiblissant II",
	["Wound Poison III"] = "Poison affaiblissant III",
	["Wound Poison IV"] = "Poison affaiblissant IV",
	["Wound Poison V"] = "Poison affaiblissant V",
	["Deadly Poison"] = "Poison mortel",
	["Deadly Poison II"] = "Poison mortel II",
	["Deadly Poison III"] = "Poison mortel III",
	["Deadly Poison IV"] = "Poison mortel IV",
	["Deadly Poison V"] = "Poison mortel V",
	["Deadly Poison VI"] = "Poison mortel VI",
	["Deadly Poison VII"] = "Poison mortel VII",	    
	["Mind-numbing Poison"] = "Poison de distraction mentale",
	["Mind-numbing Poison II"] = "Poison de distraction mentale II",
	["Mind-numbing Poison III"] = "Poison de distraction mentale III",
	["Crippling Poison"] = "Poison douloureux",
	["Crippling Poison II"] = "Poison douloureux II",
	
	["Rough Sharpening Stone"] = "Pierre à aiguiser brute",
	["Coarse Sharpening Stone"] = "Pierre à aiguiser grossière",
	["Heavy Sharpening Stone"] = "Pierre à aiguiser lourde",
	["Solid Sharpening Stone"] = "Pierre à aiguiser solide",
	["Dense Sharpening Stone"] = "Pierre à aiguiser dense",
	["Elemental Sharpening Stone"] = "Pierre à aiguiser élémentaire",
	["Fel Sharpening Stone"] = "Pierre à aiguiser gangrée",
	["Adamantite Sharpening Stone"] = "Pierre à aiguiser adamantine",
	["Rough Weightstone"] = "Silex à aiguiser brut",
	["Coarse Weightstone"] = "Silex à aiguiser grossier",
	["Heavy Weightstone"] = "Silex à aiguiser lourd",
	["Solid Weightstone"] = "Silex à aiguiser solide",
	["Dense Weightstone"] = "Silex à aiguiser dense",
	["Fel Weightstone"] = "Pierre de lest gangrenée",
	["Adamantite Weightstone"] = "Pierre de lest adamantite",

	["Wizard Oil"] = "Huile de sorcier",
	["Minor Wizard Oil"] = "Huile de sorcier mineure",
	["Lesser Wizard Oil"] = "Huile de sorcier inférieure",
	["Brilliant Wizard Oil"] = "Huile de sorcier brillante",
	["Superior Wizard Oil"] = "Huile de sorcier excellente",
	["Blessed Wizard Oil"] = "Huile de sorcier bénite",
	["Mana Oil"] = "Huile de mana",
	["Minor Mana Oil"] = "Huile de mana mineure",
	["Lesser Mana Oil"] = "Huile de mana inférieure",
	["Brilliant Mana Oil"] = "Huile de mana brillante",
	["Superior Mana Oil"] = "Huile de mana excellente",
	
	["Windfury"] = "Furie-des-vents",
	["Flametongue"] = "Langue de feu",
	["Rockbiter"] = "Croque-roc",
	["Frostbrand"] = "Arme de givre",
	
	["Omen of Clarity"] = "Augure de Clarté",
	
	["Shiny Bauble"] = "Verroterie brillante",
	["Aquadynamic Fish Lens"] = "Oeil de poisson aquadynamique",
	["Nightcrawlers"] = "Asticots",
	["Bright Baubles"] = "Verroterie",
	["Flesh Eating Worm"] = "Ver mangeur de chair",
	["Aquadynamic Fish Attractor"] = "Attracteur de poissons aquadynamique",
	
	["heavy netherweave bandage"] = "bandage épais en tisse-néant",
	["heavy frostweave bandage"] = "bandage épais en tisse-givre",
	["dreamless sleep"] = "sommeil sans rêve",
	["unstable affliction"] = "affliction instable",
	--thunderfury
	
};

VFL.Internationalize("frFR", RDX_translation);

